/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingRouteImport } from './routes/_landing'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as LandingIndexRouteImport } from './routes/_landing/index'
import { Route as AppAppRouteImport } from './routes/app/_app'
import { Route as AuthAuthRouteImport } from './routes/auth/_auth'
import { Route as AppAppIndexRouteImport } from './routes/app/_app/index'
import { Route as AppAppAccountsRouteImport } from './routes/app/_app/accounts'
import { Route as AppAppHoldingsRouteImport } from './routes/app/_app/holdings'
import { Route as AppAppPlanRouteImport } from './routes/app/_app/plan'
import { Route as AppAppSettingsRouteImport } from './routes/app/_app/settings'
import { Route as AppAppSpendRouteImport } from './routes/app/_app/spend'
import { Route as AuthAuthLoginRouteImport } from './routes/auth/_auth/login'
import { Route as AuthAuthRecoveryRouteImport } from './routes/auth/_auth/recovery'
import { Route as AuthAuthSignupRouteImport } from './routes/auth/_auth/signup'

const LandingRoute = LandingRouteImport.update({
  id: '/_landing',
  getParentRoute: () => rootRouteImport,
} as any)
const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingIndexRoute = LandingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LandingRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/app/_app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthRoute = AuthAuthRouteImport.update({
  id: '/auth/_auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppAccountsRoute = AppAppAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppHoldingsRoute = AppAppHoldingsRouteImport.update({
  id: '/holdings',
  path: '/holdings',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppPlanRoute = AppAppPlanRouteImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSpendRoute = AppAppSpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => AppAppRoute,
} as any)
const AuthAuthLoginRoute = AuthAuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthRecoveryRoute = AuthAuthRecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => AuthAuthRoute,
} as any)
const AuthAuthSignupRoute = AuthAuthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => AuthAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LandingIndexRoute
  '/unlock': typeof UnlockRoute
  '/app': typeof AppAppRouteWithChildren
  '/auth': typeof AuthAuthRouteWithChildren
  '/app/accounts': typeof AppAppAccountsRoute
  '/app/holdings': typeof AppAppHoldingsRoute
  '/app/plan': typeof AppAppPlanRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/spend': typeof AppAppSpendRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/recovery': typeof AuthAuthRecoveryRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/unlock': typeof UnlockRoute
  '/auth': typeof AuthAuthRouteWithChildren
  '/': typeof LandingIndexRoute
  '/app/accounts': typeof AppAppAccountsRoute
  '/app/holdings': typeof AppAppHoldingsRoute
  '/app/plan': typeof AppAppPlanRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/spend': typeof AppAppSpendRoute
  '/auth/login': typeof AuthAuthLoginRoute
  '/auth/recovery': typeof AuthAuthRecoveryRoute
  '/auth/signup': typeof AuthAuthSignupRoute
  '/app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_landing': typeof LandingRouteWithChildren
  '/unlock': typeof UnlockRoute
  '/app/_app': typeof AppAppRouteWithChildren
  '/auth/_auth': typeof AuthAuthRouteWithChildren
  '/_landing/': typeof LandingIndexRoute
  '/app/_app/accounts': typeof AppAppAccountsRoute
  '/app/_app/holdings': typeof AppAppHoldingsRoute
  '/app/_app/plan': typeof AppAppPlanRoute
  '/app/_app/settings': typeof AppAppSettingsRoute
  '/app/_app/spend': typeof AppAppSpendRoute
  '/auth/_auth/login': typeof AuthAuthLoginRoute
  '/auth/_auth/recovery': typeof AuthAuthRecoveryRoute
  '/auth/_auth/signup': typeof AuthAuthSignupRoute
  '/app/_app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/unlock'
    | '/app'
    | '/auth'
    | '/app/accounts'
    | '/app/holdings'
    | '/app/plan'
    | '/app/settings'
    | '/app/spend'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/signup'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/unlock'
    | '/auth'
    | '/'
    | '/app/accounts'
    | '/app/holdings'
    | '/app/plan'
    | '/app/settings'
    | '/app/spend'
    | '/auth/login'
    | '/auth/recovery'
    | '/auth/signup'
    | '/app'
  id:
    | '__root__'
    | '/_landing'
    | '/unlock'
    | '/app/_app'
    | '/auth/_auth'
    | '/_landing/'
    | '/app/_app/accounts'
    | '/app/_app/holdings'
    | '/app/_app/plan'
    | '/app/_app/settings'
    | '/app/_app/spend'
    | '/auth/_auth/login'
    | '/auth/_auth/recovery'
    | '/auth/_auth/signup'
    | '/app/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LandingRoute: typeof LandingRouteWithChildren
  UnlockRoute: typeof UnlockRoute
  AppAppRoute: typeof AppAppRouteWithChildren
  AuthAuthRoute: typeof AuthAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_landing': {
      id: '/_landing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_landing/': {
      id: '/_landing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LandingIndexRouteImport
      parentRoute: typeof LandingRoute
    }
    '/app/_app': {
      id: '/app/_app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/_auth': {
      id: '/auth/_auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/accounts': {
      id: '/app/_app/accounts'
      path: '/accounts'
      fullPath: '/app/accounts'
      preLoaderRoute: typeof AppAppAccountsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/holdings': {
      id: '/app/_app/holdings'
      path: '/holdings'
      fullPath: '/app/holdings'
      preLoaderRoute: typeof AppAppHoldingsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/plan': {
      id: '/app/_app/plan'
      path: '/plan'
      fullPath: '/app/plan'
      preLoaderRoute: typeof AppAppPlanRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/settings': {
      id: '/app/_app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/app/_app/spend': {
      id: '/app/_app/spend'
      path: '/spend'
      fullPath: '/app/spend'
      preLoaderRoute: typeof AppAppSpendRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/auth/_auth/login': {
      id: '/auth/_auth/login'
      path: '/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthAuthLoginRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/auth/_auth/recovery': {
      id: '/auth/_auth/recovery'
      path: '/recovery'
      fullPath: '/auth/recovery'
      preLoaderRoute: typeof AuthAuthRecoveryRouteImport
      parentRoute: typeof AuthAuthRoute
    }
    '/auth/_auth/signup': {
      id: '/auth/_auth/signup'
      path: '/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthAuthSignupRouteImport
      parentRoute: typeof AuthAuthRoute
    }
  }
}

interface LandingRouteChildren {
  LandingIndexRoute: typeof LandingIndexRoute
}

const LandingRouteChildren: LandingRouteChildren = {
  LandingIndexRoute: LandingIndexRoute,
}

const LandingRouteWithChildren =
  LandingRoute._addFileChildren(LandingRouteChildren)

interface AppAppRouteChildren {
  AppAppAccountsRoute: typeof AppAppAccountsRoute
  AppAppHoldingsRoute: typeof AppAppHoldingsRoute
  AppAppPlanRoute: typeof AppAppPlanRoute
  AppAppSettingsRoute: typeof AppAppSettingsRoute
  AppAppSpendRoute: typeof AppAppSpendRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppAccountsRoute: AppAppAccountsRoute,
  AppAppHoldingsRoute: AppAppHoldingsRoute,
  AppAppPlanRoute: AppAppPlanRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppSpendRoute: AppAppSpendRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AuthAuthRouteChildren {
  AuthAuthLoginRoute: typeof AuthAuthLoginRoute
  AuthAuthRecoveryRoute: typeof AuthAuthRecoveryRoute
  AuthAuthSignupRoute: typeof AuthAuthSignupRoute
}

const AuthAuthRouteChildren: AuthAuthRouteChildren = {
  AuthAuthLoginRoute: AuthAuthLoginRoute,
  AuthAuthRecoveryRoute: AuthAuthRecoveryRoute,
  AuthAuthSignupRoute: AuthAuthSignupRoute,
}

const AuthAuthRouteWithChildren = AuthAuthRoute._addFileChildren(
  AuthAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LandingRoute: LandingRouteWithChildren,
  UnlockRoute: UnlockRoute,
  AppAppRoute: AppAppRouteWithChildren,
  AuthAuthRoute: AuthAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
