/// <reference lib="webworker" />
// Privance service worker: Workbox-powered offline support.
// Built by scripts/build-sw.mjs via injectManifest. The __WB_MANIFEST
// placeholder is replaced at build time with a revisioned precache manifest.

import { clientsClaim } from "workbox-core";
import { createHandlerBoundToURL, precacheAndRoute } from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";
import { CacheFirst, NetworkFirst, NetworkOnly } from "workbox-strategies";

// Auto-generated by injectManifest: covers all Vite hashed chunk filenames.
// @ts-expect-error __WB_MANIFEST is injected by workbox-build
precacheAndRoute(self.__WB_MANIFEST);

// skipWaiting is message-gated (below), never called on install, so a new
// worker waits until every tab closes or the user accepts the update banner: a
// version swap never lands mid crypto flow. clientsClaim only acts after that.
clientsClaim();

// Cross-origin requests (e.g. price lookups) bypass the cache entirely.
registerRoute(({ url }) => url.origin !== self.location.origin, new NetworkOnly());

// ZK constraint: never cache API responses (ciphertext auth boundary).
registerRoute(({ url }) => url.pathname.startsWith("/api/"), new NetworkOnly());

// Long-lived crypto assets: WASM, workers, KDF.
registerRoute(
  ({ url }) => /\.(wasm|mjs)$/.test(url.pathname) || url.pathname.includes("/kdf/"),
  new CacheFirst(),
);

// SPA app shell: every navigation renders from the precached index.html, so
// deep links and offline reloads resolve without a network round-trip.
registerRoute(new NavigationRoute(createHandlerBoundToURL("/index.html")));

// Other same-origin static assets (hashed JS/CSS/fonts/icons): network-first.
registerRoute(({ request }) => request.destination !== "document", new NetworkFirst());

// Allow the update banner to trigger skipWaiting for an immediate update.
self.addEventListener("message", (event) => {
  if (event.data?.type === "SKIP_WAITING") self.skipWaiting();
});
