[test]
coverage = true
coverageThreshold = { lines = 0.85, functions = 0.85, statements = 0.85 }
coverageReporter = ["text", "lcov"]
coveragePathIgnorePatterns = ["**/*.test.ts", "**/index.ts", "**/repo.ts"]
